In [1]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install torchaudio

In [90]:
from torch.utils.data import Dataset
import pandas as pd
import torchaudio
import os
import librosa

class DCASE_Data(Dataset):

  def __init__(self, annotations_dict, audio_dir):
    self.annotations = annotations_dict 
    self.audio_dir = audio_dir

  def __len__(self, set):
    if set == "birdvox":
      annotations = pd.read_csv(self.annotations["birdvox"]) 
    elif set == "freefield":
      annotations = pd.read_csv(self.annotations["freefield"]) 
    elif set == "warblr":
      annotations = pd.read_csv(self.annotations["warblr"])

    return len(annotations)

  def __getitem__(self, set, index):
    audio_sample_path, annotations = self._get_audio_sample_path(set, index)
    label = self._get_audio_sample_label(annotations, index)
    filename = self._get_filename(annotations, index)
    signal, sr = torchaudio.load(audio_sample_path) 
    return signal, label, filename

  def _get_audio_sample_path(self, set, index):
    if set == "birdvox":
      annotations = pd.read_csv(self.annotations["birdvox"]) 
      fold = f"{annotations.iloc[index, 1]}"
      path = os.path.join(self.audio_dir, fold, f"{annotations.iloc[index, 0]}.wav")
    elif set == "freefield":
      annotations = pd.read_csv(self.annotations["freefield"]) 
      fold = f"{annotations.iloc[index, 1]}"
      path = os.path.join(self.audio_dir, fold, f"{annotations.iloc[index, 0]}.wav")
    elif set == "warblr":
      annotations = pd.read_csv(self.annotations["warblr"]) 
      fold = f"{annotations.iloc[index, 1]}"
      path = os.path.join(self.audio_dir, fold, f"{annotations.iloc[index, 0]}.wav")
    
    return path, annotations

  def _get_audio_sample_label(self, annotations, index):
    return annotations.iloc[index, 2]

  def _get_filename(self, annotations, index):
    return annotations.iloc[index, 0]

if __name__ == "__main__":

  ANNOTATIONS_DICT = {
      "birdvox": '/content/drive/My Drive/DCASE_Datasets/labels/BirdVox-DCASE20k.csv',
      "freefield": '/content/drive/My Drive/DCASE_Datasets/labels/ff1010bird.csv',
      "warblr": '/content/drive/My Drive/DCASE_Datasets/labels/warblrb10k.csv'
  }

  AUDIO_DIR = '/content/drive/My Drive/DCASE_Datasets/audio/'

  data = DCASE_Data(ANNOTATIONS_DICT, AUDIO_DIR)


  print(f"There are {data.__len__('birdvox')} samples in the dataset.")
  signal, label, filename = data.__getitem__('birdvox', 0)
  print(signal.shape, label, filename)
  print(signal)
  print()

  print(f"There are {data.__len__('freefield')} samples in the dataset.")
  signal, label, filename = data.__getitem__('freefield', 0)
  print(signal.shape, label, filename)
  print(signal)
  print()

  print(f"There are {data.__len__('warblr')} samples in the dataset.")
  signal, label, filename = data.__getitem__('warblr', 0)
  print(signal.shape, label, filename)
  print(signal)
  print()


There are 20000 samples in the dataset.
torch.Size([1, 441000]) 1 00053d90-e4b9-4045-a2f1-f39efc90cfa9
tensor([[ 0.0056,  0.0042, -0.0105,  ...,  0.0031,  0.0017, -0.0012]])

There are 7690 samples in the dataset.
torch.Size([1, 441000]) 0 64486
tensor([[-0.0729, -0.0900, -0.0634,  ...,  0.0149,  0.0164,  0.0174]])

There are 8000 samples in the dataset.
torch.Size([1, 444416]) 1 759808e5-f824-401e-9058
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0170, 0.0226, 0.0189]])

